# Generated by Django 5.0.6 on 2024-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
