# Generated by Django 5.0.6 on 2024-07-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_basket_created_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
